### PR TITLE
Button hover + Linear gradient

### PR DESCRIPTION
**Pull request by TheShadowDragon**

### CODE REVIEW

**Comment by bigjango13** [comment]
Looks good, but could you make it quicker?

**Comment by bigjango13** [comment]
No I mean the speed of the animation, it seems a bit long.

**Comment by TheShadowDragon** [comment]
Never created a pull request before with github. How do I edit the request? The fix would be   transition-duration: 0.4s;
 to   transition-duration: 0.2s;

**Comment by bigjango13** [comment]
All you have to do is edit the [file](https://github.com/TheShadowDragon/bark-it/edit/main/index.html) and it will be add to the pull request.

**Comment by TheShadowDragon** [comment]
I think I did something wrong the first time I created the pull request.

**Pull request closed without merging**
